export const TOKEN_KEY = 'token'
export const USER_NAME = 'name'
export const PASSWORD = 'password'
export const USER_INFO_KEY = 'user_info'
export const USER_MENUS_KEY = 'user_menus'
export const USER_PERMISSION_KEY = 'user_permission'
